---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-config
  annotations:
    description: Custom StackStorm config which will apply settings on top of default st2.conf
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # TODO: Bundle DB/MQ login secrets in dynamic ENV-based st2.secrets.conf, leave custom user-defined settings for st2.user.conf (?)
  # Docker/K8s-based st2 config file used for templating service names and common overrides on top of original st2.conf.
  # The order of merging: st2.conf < st2.docker.conf < st2.user.conf
  st2.docker.conf: |
    [auth]
    api_url = http://{{ .Release.Name }}-st2api{{ template "enterpriseSuffix" . }}:9101/
    {{- if index .Values "etcd-operator" "enabled" }}
    [coordination]
    url = etcd://{{ index .Values "etcd-operator" "etcdCluster" "name" }}-client:2379
    {{- end }}
    {{- if index .Values "rabbitmq-ha" "enabled" }}
    [messaging]
    url = amqp://{{ required "rabbitmq-ha.rabbitmqUsername is required!" (index .Values "rabbitmq-ha" "rabbitmqUsername") }}:{{ required "rabbitmq-ha.rabbitmqPassword is required!" (index .Values "rabbitmq-ha" "rabbitmqPassword") }}@{{ .Release.Name }}-rabbitmq-ha-discovery:5672
    {{- end }}
    {{- if index .Values "mongodb-ha" "enabled" }}
    [database]
    {{- if index .Values "mongodb-ha" "auth" "enabled" }}
    host = mongodb://{{ template "mongodb-ha-nodes" $ }}/?authSource=admin&replicaSet={{ index .Values "mongodb-ha" "replicaSetName" }}
    username = {{ required "mongodb-ha.auth.adminUser is required!" (index .Values "mongodb-ha" "auth" "adminUser") }}
    password = {{ required "mongodb-ha.auth.adminPassword is required!" (index .Values "mongodb-ha" "auth" "adminPassword") }}
    {{- else }}
    host = mongodb://{{ template "mongodb-ha-nodes" $ }}/?replicaSet={{ index .Values "mongodb-ha" "replicaSetName" }}
    {{- end }}
    port = {{ index .Values "mongodb-ha" "port" }}
    {{- end }}
    {{- if .Values.secrets.st2.datastore_crypto_key }}
    [keyvalue]
    encryption_key_path = /etc/st2/keys/datastore_key.json
    {{- end }}

  # User-defined st2 config with custom settings applied on top of everything else.
  # The order of merging: st2.conf < st2.docker.conf < st2.user.conf
  st2.user.conf: |
{{ .Values.st2.config | indent 4 }}
