{{- if .Values.secrets.st2.datastore_crypto_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-datastore-crypto-key
  annotations:
    description: StackStorm crypto key used to encrypt/decrypt KV records
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  # Datastore key used to encrypt/decrypt record for the KV store
  datastore_crypto_key: {{ .Values.secrets.st2.datastore_crypto_key | b64enc }}

{{- end }}
