{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stackstorm-ha.serviceAccountName" . }}
  {{- if .Values.serviceAccount.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.serviceAccount.serviceAccountAnnotations | indent 4 }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "stackstorm-ha.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
{{- end }}
