apiVersion: apps/v1
kind: Deployment
metadata:
  name: st2-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: st2-operator
  template:
    metadata:
      labels:
        name: st2-operator
    spec:
      serviceAccountName: st2-operator
      containers:
        - name: st2-operator
          # Replace this with the built image name
          image: cvignola/st2-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "st2-operator"
